[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bot"
description = ""
version = "0.0.1"
authors = [
    { name = "vasgg", email = "vas.g@me.com" },
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.14"

dependencies = [
    "aiogram>=3.26.0",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "greenlet>=3.3.2",
    "pydantic-settings>=2.13.1",
    "redis>=7.3.0",
    "ruff>=0.15.6",
    "sqlalchemy>=2.0.48",

]
typing = [
    "ty>=0.0.23",
]
test = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
]
dev = [
    { include-group = "typing" },
    { include-group = "test" },
    "pre-commit>=4.5.1",
]

[tool.ruff]
line-length = 119
target-version = "py314"
exclude = [
    "alembic",
]

[project.scripts]
bot-run = "bot.main:run_main"
